### PR TITLE
feat: support solana

### PR DESCRIPTION
**Pull request by witter-deland**
## Summary by CodeRabbit

- **New Features**
	- Introduced a new `SolanaChainWallet` class with enhanced wallet functionalities for the Solana blockchain.
	- Added constants related to the Solana blockchain in a new file.

- **Dependency Updates**
	- Updated the version of `@solana/web3.js`.
	- Added new dependencies: `@solana/spl-token`, `bignumber.js`, `@delandlabs/coin-base`, and `tweetnacl`.

- **Bug Fixes**
	- Improved error handling for wallet operations.

- **Tests**
	- Enhanced test file handling by utilizing system temporary directories.
	- Removed outdated test files for BIP32 and hashing functionalities, which may impact testing coverage.

### CODE REVIEW

**Comment by witter-deland** [comment]
@coderabbitai review

**Comment by witter-deland** [comment]
@coderabbitai review

**Review by rustin01 — APPROVED** [review]

**Comment by witter-deland** [comment]
https://github.com/coderabbitai review

**Comment by witter-deland** [comment]
@coderabbitai review

**Comment by witter-deland** [comment]
@coderabbitai review

**Comment by witter-deland** [comment]
@coderabbitai review

**Review by rustin01 — APPROVED** [review]

**Pull request merged**
